# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a26040c553a465fef00db541636f29f6"
application_url = "https://ty-beverage-locks-terror.trycloudflare.com"
embedded = true
name = "Gift Rush"
handle = "gift-rush"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://ty-beverage-locks-terror.trycloudflare.com/auth/callback",
  "https://ty-beverage-locks-terror.trycloudflare.com/auth/shopify/callback",
  "https://ty-beverage-locks-terror.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
